export const routeSteps = [
  {
    id: 'prepare',
    phase: 'Before you start',
    title: 'Prepare accounts and safety basics',
    summary: 'Gather IDs, banking access, MetaMask, 2FA, and a safe seed phrase plan.',
    detail: 'This is the quiet setup pass. It prevents most expensive mistakes before any money moves.',
    time: '20-40 min',
    fee: 'Free',
    riskLevel: 'High safety value',
    checklist: [
      'Bank of Taiwan online banking is ready',
      'Taiwan ID or ARC is available for KYC',
      'MetaMask is installed from the official source',
      'Seed phrase is backed up offline on paper',
      'DBS and Singpass are ready if using the SGD route',
    ],
    warning: 'Never screenshot, cloud-save, email, or share your MetaMask seed phrase.',
  },
  {
    id: 'taiwan',
    phase: 'Taiwan on-ramp',
    title: 'Choose a registered Taiwan exchange',
    summary: 'MAX Exchange or BitoPro are the beginner-friendly Taiwan on-ramp choices.',
    detail: 'Use an FSC-registered exchange, then link your Bank of Taiwan account for a TWD transfer.',
    time: '1-3 days KYC',
    fee: 'TWD deposit free',
    riskLevel: 'Use regulated providers',
    checklist: [
      'Create account on MAX Exchange or BitoPro',
      'Confirm the provider is FSC registered',
      'Enable 2FA with an authenticator app',
      'Link your Bank of Taiwan account',
    ],
    warning: 'Avoid unofficial apps, social links, or providers that cannot clearly identify their registration status.',
  },
  {
    id: 'kyc',
    phase: 'Identity check',
    title: 'Complete KYC and security setup',
    summary: 'Upload ID, verify phone/email, and wait for approval before depositing funds.',
    detail: 'KYC is the slowest part of the first route. After it is approved, repeat transfers are much faster.',
    time: '1-3 business days',
    fee: 'Free',
    riskLevel: 'Privacy sensitive',
    checklist: [
      'Upload Taiwan ID or ARC',
      'Verify phone and email',
      'Store exchange recovery codes safely',
      'Wait for account approval before sending TWD',
    ],
    warning: 'Do not send documents through chat support unless you are inside the official provider app or site.',
  },
  {
    id: 'buy',
    phase: 'Exchange action',
    title: 'Deposit TWD and buy crypto',
    summary: 'Transfer TWD early in the day, then buy USDT or another supported asset.',
    detail: 'Most users buy USDT first because stablecoins are easier to move and compare across networks.',
    time: 'Same day',
    fee: '~0.2% trading',
    riskLevel: 'Price/spread risk',
    checklist: [
      'Deposit TWD from Bank of Taiwan',
      'Check the credited exchange balance',
      'Buy USDT, ETH, BTC, or SOL as needed',
      'Save trade confirmation for records',
    ],
    warning: 'Market price and spread can move while you wait. Check the final received amount before confirming.',
  },
  {
    id: 'metamask',
    phase: 'Self-custody',
    title: 'Withdraw from exchange to MetaMask',
    summary: 'Choose the correct network, paste the MetaMask address, and send a small test first.',
    detail: 'This is the highest-risk action. The withdrawal network must match the receiving token/network support.',
    time: '1-30 min',
    fee: 'Low on Tron/Arbitrum',
    riskLevel: 'Network mismatch risk',
    checklist: [
      'Open the correct receiving account in MetaMask',
      'Choose the same token and network on the exchange',
      'Paste and verify first/last wallet characters',
      'Send a small test transfer for first-time routes',
      'Save the transaction hash',
    ],
    warning: 'Sending funds on the wrong network may make recovery difficult or impossible.',
  },
  {
    id: 'choose',
    phase: 'Route branch',
    title: 'Choose what happens after MetaMask',
    summary: 'Pick direct spending convenience or convert back to SGD and withdraw to DBS.',
    detail: 'The app will tailor the next step and progress summary based on this choice.',
    time: '1 min',
    fee: 'Depends on path',
    riskLevel: 'Route decision',
    checklist: [
      'Decide whether you need actual bank cash or card spending',
      'Check current network support before moving funds',
      'Keep enough buffer for fees or FX conversion',
    ],
    warning: 'Do not choose a route only by fee. Liquidity, support, and record keeping matter too.',
  },
  {
    id: 'spend',
    branch: 'spend',
    phase: 'Spend crypto',
    title: 'Fund card or payment route',
    summary: 'Use a supported spending route such as a card flow, wallet payment, or Hawala-style top-up.',
    detail: 'For Hawala-style spending, pre-fund with the supported stablecoin and network before topping up the virtual card.',
    time: 'Minutes after setup',
    fee: 'Network + FX',
    riskLevel: 'Token/network support',
    checklist: [
      'Confirm the card or payment route is available in Singapore',
      'Generate the correct deposit address',
      'Use the supported token and network',
      'Top up the card balance after deposit arrives',
      'Keep payment and top-up records',
    ],
    warning: 'A spending card usually requires pre-funding; it does not pull directly from MetaMask at checkout.',
  },
  {
    id: 'dbs',
    branch: 'dbs',
    phase: 'SGD off-ramp',
    title: 'Sell to SGD and withdraw to DBS',
    summary: 'Send crypto to a Singapore exchange, sell for SGD, then withdraw by FAST to DBS.',
    detail: 'OKX Singapore is the cheapest path in the guide; Crypto.com is beginner-friendly but may charge withdrawal fees.',
    time: 'Same day after KYC',
    fee: '0.1%-0.2% + FAST free',
    riskLevel: 'Exchange deposit risk',
    checklist: [
      'Complete Singpass KYC on a Singapore exchange',
      'Copy the deposit address from the exchange',
      'Send from MetaMask on the matching network',
      'Sell crypto for SGD',
      'Withdraw SGD to DBS via FAST',
    ],
    warning: 'Always confirm the Singapore exchange deposit network before sending from MetaMask.',
  },
  {
    id: 'records',
    phase: 'After transfer',
    title: 'Verify and archive records',
    summary: 'Keep exchange confirmations, transaction hashes, fees, screenshots, and bank receipts.',
    detail: 'Good records make future tax, audit, or support questions much easier to answer.',
    time: '10-20 min',
    fee: 'Free',
    riskLevel: 'Compliance hygiene',
    checklist: [
      'Confirm DBS deposit or card top-up received',
      'Save exchange and wallet transaction details',
      'Record exchange rates and network fees',
      'Store receipts in one folder',
    ],
    warning: 'Tax and reporting rules can change. Keep records for several years and consult a qualified advisor.',
  },
];

export const routeSummary = {
  spend: 'Best when you want mobile wallet or card spending without repeated bank withdrawals.',
  dbs: 'Best when you need SGD in your bank account for local transfers, bills, or cash planning.',
};

export const providerRows = [
  { name: 'MAX Exchange', bestFor: 'Taiwan beginner on-ramp', fee: '~0.2% trading', timing: '1-3 day KYC' },
  { name: 'BitoPro', bestFor: 'Taiwan backup option', fee: '~0.2% trading', timing: '1-3 day KYC' },
  { name: 'OKX Singapore', bestFor: 'SGD off-ramp', fee: '~0.1%-0.2%', timing: '1-2 day KYC' },
  { name: 'Crypto.com', bestFor: 'Beginner-friendly app', fee: '~0.1%-0.5%', timing: '1-2 day KYC' },
  { name: 'Hawala-style card', bestFor: 'Direct spending route', fee: 'Network + FX', timing: 'Fast after setup' },
];

export const recordItems = [
  'KYC approval',
  'Bank transfer record',
  'Trade confirmation',
  'Wallet address',
  'Transaction hash',
  'Network fee',
  'Exchange rate',
  'DBS deposit or card top-up',
  'Final receipt screenshot',
];
